server:
  port: 8080
spring:
  application:
    name: cattle-farm-cowfarm #指定服务名
  datasource:
    druid:
      url: jdbc:mysql://office.ihaier.online:23306/cow_farm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: qwe123!@#ASD
#      url: jdbc:mysql://172.16.0.11:3306/cow_farm?useUnicode=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: qwe123!@#ASD
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  jpa:
    database: MySQL
    show-sql: true

pagehelper:
  helper-dialect: mysql

jwt:
  config:
    key: cosmoplat
    ttl: 3600000

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.cosmoplat.cowfarm.mapper: debug
